### ISSUE TITLE
Cannot run git commands whilst prompt is being generated

### ISSUE THREAD

**Issue by pjcj** [woefe/git-prompt.zsh#18] opened 2020-03-04 13:41 UTC
Running a git command whilst the prompt is still being generated in the background can lead to errors such as "fatal: Unable to create '.../.git/index.lock': File exists."

Is there a possibility to terminate the background process as soon as a command is run, or to solve this in some other way?

A lot of the benefit of this lovely prompt is lost if you have to remember not to run any git commands until the prompt has been generated.

**Comment by woefe** [comment] 2020-03-04 20:18
Thanks for your report. I was able to reproduce the issue. Running another `git status` is not a problem, but commands like `add` or `commit` that change things won't run, if you are fast enough.

I don't know why `git status` would lock the index. Maybe there is a way to prevent it. Otherwise we could indeed kill the background process.

**Comment by rnc** [comment] 2020-03-04 20:22
@woefe It looks like status can alter the index according to https://git-scm.com/docs/git-status (See background refresh) Perhaps add `--no-optional-locks` ?

**Comment by woefe** [comment] 2020-03-04 21:00
Thanks @rnc! That did it. The manpage even recommends that we should have used that option right from the beginning. 

> Scripts running status in the background should consider using `git --no-optional-locks status`

Fixed in 81fdeb4

**Closed by woefe** 2020-03-04 21:00 UTC
